version: '3'
services:
    mybox:
        build:
            context: ./docker-config
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: mybox
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - mybox
        depends_on:
            - mysql
    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'yousef'
            MYSQL_DATABASE: 'mybox_beta_test'
            MYSQL_USER: 'yousef'
            MYSQL_PASSWORD: 'yousef'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'myboxmysql:/var/lib/mysql'
        networks:
            - mybox
networks:
    mybox:
        driver: bridge
volumes:
    myboxmysql:
        driver: local





